### ISSUE TITLE
Error: Non-base58 character

### ISSUE THREAD

**Issue by sukeerthimogallapalli** [bitpay/bitcore-lib-cash#30]
i am able to create address and privatekey of bitcoin cash address but when i am passing it to transation object it is giving error

My code:

const explorers = require('bitcore-explorers')

const insight = new explorers.Insight('https://test-bch-insight.bitpay.com')
const bch = require('bitcore-lib-cash');

const privateKey = "a413850d0dacf99354bf033bd4b56b29c154b6faf7ecb308f72040505050f15c"
var address ="qp8fcq4v80quevnzj3mapqnfw7rhf4q20u3940rzyz"

insight.getUnspentUtxos(address, function (error, utxos) {
    if (error) {
      console.error(error)
      return
    }else{
        console.log('===================',utxos)
    }
})

i am getting this error with above code

/home/ahex/Desktop/tokenize.node/node_modules/bitcore-explorers/node_modules/bitcore-lib/node_modules/bs58/lib/bs58.js:51
    if (!(c in ALPHABET_MAP)) throw new Error('Non-base58 character')
                              ^

Error: Non-base58 character
    at Object.decode (/home/ahex/Desktop/tokenize.node/node_modules/bitcore-explorers/node_modules/bitcore-lib/node_modules/bs58/lib/bs58.js:51:37)
    at Function.Base58.decode (/home/ahex/Desktop/tokenize.node/node_modules/bitcore-explorers/node_modules/bitcore-lib/lib/encoding/base58.js:48:26)
    at Function.Base58Check.decode (/home/ahex/Desktop/tokenize.node/node_modules/bitcore-explorers/node_modules/bitcore-lib/lib/encoding/base58check.js:45:31)
    at Function.Address._transformString (/home/ahex/Desktop/tokenize.node/node_modules/bitcore-explorers/node_modules/bitcore-lib/lib/address.js:279:35)
    at Address._classifyArguments (/home/ahex/Desktop/tokenize.node/node_modules/bitcore-explorers/node_modules/bitcore-lib/lib/address.js:107:20)
    at new Address (/home/ahex/Desktop/tokenize.node/node_modules/bitcore-explorers/node_modules/bitcore-lib/lib/address.js:73:19)
    at /home/ahex/Desktop/tokenize.node/node_modules/bitcore

**Comment by sukeerthimogallapalli** [comment]
Maybe you could call insight.getUnspentUtxos with bch.Address.fromString("qqmrvwmyludwj05grf9g69enlhpfzn2gzcrznru8k3").toLegacyAddress() rather than just address.
