### ISSUE TITLE
bitcore-lib-cash error while running insight-api with translateAddresses

### ISSUE THREAD

**Issue by bijakatlykkex** [bitpay/bitcore-lib-cash#9]
Hello,

When I create a bitcore node for Bitcoin Cash with insight-api (I clone both bitcoe-lib-cash and insight-api the cash branch from github), everything runs fine until I configure insight-api with "translateAddresses" : true.

At this point if I get a url like http://127.0.0.1:3001/insight-api/addr/qrkghdyvptkr3da56hq0zu03jry2cvccys5845kpp2/utxo I get an error similar to following;

`[addresses.js.130] TypeError: D.eqn is not a function`
`    at polymod (/home/lykkex/bccnode25/node_modules/bitcore-lib-cash/lib/address.js:767:13)`
`    at validChecksum (/home/lykkex/bccnode25/node_modules/bitcore-lib-cash/lib/address.js:295:12)`
`    at decodeCashAddress (/home/lykkex/bccnode25/node_modules/bitcore-lib-cash/lib/address.js:325:10)`
`    at Function.Address._transformString (/home/lykkex/bccnode25/node_modules/bitcore-lib-cash/lib/address.js:391:16)`
`    at Address._classifyArguments (/home/lykkex/bccnode25/node_modules/bitcore-lib-cash/lib/address.js:111:20)`
`    at new Address (/home/lykkex/bccnode25/node_modules/bitcore-lib-cash/lib/address.js:77:19)`
`    at /home/lykkex/bccnode25/node_modules/insight-api/lib/addresstranslator.js:34:16`
`    at Function.map (/home/lykkex/bccnode25/node_modules/insight-api/node_modules/lodash/dist/lodash.js:3509:27)`
`   at Function.AddressTranslator.translate (/home/lykkex/bccnode25/node_modules/insight-api/lib/addresstranslator.js:33:16)`
`    at Function.AddressTranslator.translateInput (/home/lykkex/bccnode25/node_modules/insight-api/lib/addresstranslator.js:54:15)`

Helps appreciated,
Thanks

**Comment by bijakatlykkex** [comment]
I have created a temporary fix here: https://github.com/LykkeCity/bitcore-lib-cash/commit/6b0a213320669d10eb0307efff6cc9803754a675
